export enum SYSTEM_MODULE_CODES {
    USER_MANAGEMENT = 'USER_MANAGEMENT',
    SALES_MANAGEMENT = 'SALES_MANAGEMENT',
    SYSTEM_CONFIGURATION = 'SYSTEM_CONFIGURATION',
    ACCOUNT_MANAGEMENT = 'ACCOUNT_MANAGEMENT'
}
