export enum SERVICE_CATEGORY {
  VAPT = 'VAPT',
  GRC = 'GRC',
  AUDIT = 'AUDIT',
  ISO_STANDARDIZATION = 'ISO_STANDARDIZATION',
  TRAINING = 'TRAINING',
  CONSULTING = 'CONSULTING',
  OTHER = 'OTHER',
  REGULATORY_COMPLIANCE = 'REGULATORY_COMPLIANCE',
  
}

export enum SERVICE_TYPE {
  // VAPT Types
  WEB_VAPT = 'WEB_VAPT',
  MOBILE_VAPT = 'MOBILE_VAPT',
  NETWORK_VAPT = 'NETWORK_VAPT',
  API_VAPT = 'API_VAPT',
  CLOUD_VAPT = 'CLOUD_VAPT',
  IOT_VAPT = 'IOT_VAPT',
  SOURCE_CODE_REVIEW = 'SOURCE_CODE_REVIEW',
  
  // Mobile VAPT Sub-types
  ANDROID_VAPT = 'ANDROID_VAPT',
  IOS_VAPT = 'IOS_VAPT',
  //HYBRID_VAPT = 'HYBRID_VAPT',
  
  // GRC Types
  COMPLIANCE_AUDIT = 'COMPLIANCE_AUDIT',
  RISK_ASSESSMENT = 'RISK_ASSESSMENT',
  GOVERNANCE_CONSULTING = 'GOVERNANCE_CONSULTING',
  
  // ISO Types
  ISO_9001 = 'ISO_9001',
  ISO_27001 = 'ISO_27001',
  ISO_22301 = 'ISO_22301',
  ISO_20000 = 'ISO_20000',
  
  // Generic
  OTHER = 'OTHER'
}

export enum SERVICE_ACCESS_LEVEL {
  PUBLIC = 'PUBLIC',           // All users can see
  DEPARTMENT_ONLY = 'DEPARTMENT_ONLY',  // Only specific department
  ROLE_BASED = 'ROLE_BASED',   // Based on user role/group
  RESTRICTED = 'RESTRICTED'    // Specific users only
}

// Mapping of which user groups can access which service categories
export const SERVICE_CATEGORY_ACCESS = {
  [SERVICE_CATEGORY.VAPT]: ['VAPT_TEAM', 'MANAGER', 'SUPER_ADMIN', 'ADMIN'],
  [SERVICE_CATEGORY.GRC]: ['GRC_TEAM', 'MANAGER', 'SUPER_ADMIN', 'ADMIN'],
  [SERVICE_CATEGORY.AUDIT]: ['AUDIT_TEAM', 'MANAGER', 'SUPER_ADMIN', 'ADMIN'],
  [SERVICE_CATEGORY.ISO_STANDARDIZATION]: ['ISO_TEAM', 'MANAGER', 'SUPER_ADMIN', 'ADMIN'],
  [SERVICE_CATEGORY.TRAINING]: ['SALES_TEAM', 'MANAGER', 'SUPER_ADMIN', 'ADMIN'],
  [SERVICE_CATEGORY.CONSULTING]: ['SALES_TEAM', 'MANAGER', 'SUPER_ADMIN', 'ADMIN'],
  [SERVICE_CATEGORY.OTHER]: ['SALES_TEAM', 'MANAGER', 'SUPER_ADMIN', 'ADMIN']
};
